// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgJqFOrjhC9gWWT4M3wU4s46jyWe6hIf8',
    appId: '1:1054625543551:web:61cbef788e6cc71edc564a',
    messagingSenderId: '1054625543551',
    projectId: 'tasksync-99ab3',
    authDomain: 'tasksync-99ab3.firebaseapp.com',
    storageBucket: 'tasksync-99ab3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY1QHjkA93CA1pamr2KmX8Wq_4mAW681g',
    appId: '1:1054625543551:android:83512b7dc7ccb706dc564a',
    messagingSenderId: '1054625543551',
    projectId: 'tasksync-99ab3',
    storageBucket: 'tasksync-99ab3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMEChB_zAc-mtVnH5iqWs3wiBaI1wuLTM',
    appId: '1:1054625543551:ios:f6ed6f0c6c046799dc564a',
    messagingSenderId: '1054625543551',
    projectId: 'tasksync-99ab3',
    storageBucket: 'tasksync-99ab3.firebasestorage.app',
    iosBundleId: 'com.example.tasksync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMEChB_zAc-mtVnH5iqWs3wiBaI1wuLTM',
    appId: '1:1054625543551:ios:f6ed6f0c6c046799dc564a',
    messagingSenderId: '1054625543551',
    projectId: 'tasksync-99ab3',
    storageBucket: 'tasksync-99ab3.firebasestorage.app',
    iosBundleId: 'com.example.tasksync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgJqFOrjhC9gWWT4M3wU4s46jyWe6hIf8',
    appId: '1:1054625543551:web:e7a9cd489c00dc83dc564a',
    messagingSenderId: '1054625543551',
    projectId: 'tasksync-99ab3',
    authDomain: 'tasksync-99ab3.firebaseapp.com',
    storageBucket: 'tasksync-99ab3.firebasestorage.app',
  );
}
